### ISSUE TITLE
Discovery of sensors / energy

### ISSUE THREAD

**Issue by sweebel** [joleys/niko-home-control-II#1]
Am I correct it is still needed to manually add these lines? 
https://github.com/filipvh/hass-nhc2/issues/28#issuecomment-955585427

Saw that you where the person who made the thermostat possible :-) so thank you! 

Due the pip bug of philip's repo I installed your's as I also wanted the energy sensor.
If you need help with debugging let me know!

**Comment by joleys** [comment]
Yes, correct.  Those are needed to add the data to the Energy dashboard.  The direct value from NHC will not be accepted; this must be a totalizer.

**Comment by sweebel** [comment]
Ok thanks! 
and agree for now more than acceptable! Thanks for the effort.

**Comment by sweebel** [comment]
After some trial and error. 
My sensor / monitor was discoverd and added in the NHC integration it receive the name sensor.driefasige_elektriciteitsmeting_1
So my snippet for configuration.yaml looks like this and after a config check and restart I could find them in my lovelace ui and could add it to the energy monitor

sensor:
  - platform: integration
    source: sensor.driefasige_elektriciteitsmeting_1
    name: energy_elektriciteit
    unit_prefix: k
    round: 3
    method: left

utility_meter:
  energy_daily:
    source: sensor.driefasige_elektriciteitsmeting_1
    cycle: daily
  energy_monthly:
    source: sensor.driefasige_elektriciteitsmeting_1
    cycle: monthly
