### ISSUE TITLE
state of cover unknown

### ISSUE THREAD

**Issue by bugzke** [joleys/niko-home-control-II#10]
Hi,

Today I noticed my NHC2 covers have an unknown state in HA.

I can control them, and the up/down arrow changes whether the cover is open or closed.
So, it is picking up something, but the state open/closed is missing. Resulting in "unknown" in the history, as well as an unknown state icon.

So expecting this:
![image](https://user-images.githubusercontent.com/84719694/160841862-cf0570dc-f3e6-4737-bf35-d553820ca866.png)

But getting this:
![image](https://user-images.githubusercontent.com/84719694/160841943-e071f843-f344-47b3-88f5-a63ff37456f3.png)

This used to work in the original [hass-nhc2](https://github.com/filipvh/hass-nhc2) integration (and probably still does, but that integration has other flaws and seems to be abandoned).

**Comment by joleys** [comment]
@bugzke Can you check if the update fixes your issue?  I don't have shutters in my installation.

**Comment by bugzke** [comment]
Just installed the update: issue fixed!
