### ISSUE TITLE
Add GasVolume to Energy tab

### ISSUE THREAD

**Issue by NickDeb** [joleys/niko-home-control-II#102]
Hi guys

With the NHC app, it is possible to view my gas consumption as well.
Would it be possible to integrate into HA?

<img width="562" alt="image" src="https://github.com/joleys/niko-home-control-II/assets/149835324/d97bca45-412e-49af-9a32-2188d35ebe25">

Best Regards
Nick

**Comment by tijsverkoyen** [comment]
See https://github.com/joleys/niko-home-control-II/issues/6 also.
