### ISSUE TITLE
Integration does not show up in list

### ISSUE THREAD

**Issue by stefandec** [joleys/niko-home-control-II#103]
Hi, I am a newby to ha. I have the ha running on my synology DS with the following setup:
## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 30, 2023 at 10:32 AM
-- | --
current_recorder_run | December 30, 2023 at 1:53 PM
estimated_db_size | 0.23 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

When I go to add an integration, and I type "Niko" all I get is the old niko home control: 
(https://github.com/home-assistant/core/tree/dev/homeassistant/components/niko_home_control)

**Can you tell me how to trigger the niko-home-control-II setup?**

Thank you very much

**Comment by stefandec** [comment]
Ok, I solved it. You have to copy the contents of nhc2 folder that you find in the zip of this project into the custom_components folder inside your HA docker mapped folder. Then when you go to integrations, find Niko, the nhc2 will show up

**Comment by stefandec** [comment]
Then you will be presented with an interactive setup. Thanks to Joleys for this integration.

**Comment by tijsverkoyen** [comment]
@stefandec an even beter way is to install https://hacs.xyz/ and add this repository.

With HACS you won’t need to update the integration manually when there is an update.

**Comment by stefandec** [comment]
I will investigate. Thank you for the pointer.
As an aside, I noticed that there is a new version of the Niko Document for the API
[hobby_api_documentation_latest.pdf](https://github.com/joleys/niko-home-control-II/files/13798609/hobby_api_documentation_latest.pdf)
( I am not sure if this version is already supported in the integration )

**Comment by stefandec** [comment]
Ok, I confess I am stuck again. I installed HACS, but I do not know how to add this nhc2 integration to it. Or is the nhc2 update automatic once HACS integration is installed?

**Comment by tijsverkoyen** [comment]
@stefandec I have opened a PR where I have added the instructions on how to install the integration through HACS. See https://github.com/joleys/niko-home-control-II/pull/104/files.

Can you check if you get it installed by following these instructions?

**Comment by stefandec** [comment]
@tijsverkoyen  I guess I have it installed correctly, since when I did the step to add the custom repository to HACS, it says 
![image](https://github.com/joleys/niko-home-control-II/assets/6311264/42d5cf28-078f-475b-9935-975a4b8854c6)

I am guessing that nhc2 will not show up anywhere in hacs integrations/entities but that hacs service will go over its repositories and check for updates of any installed integrations.

I guess I will find out if hacs will auto update nhc2 when a new version comes out..
Anyway, thanks for the help, I am a complete newby to home assistant.

**Comment by tijsverkoyen** [comment]
@stefandec I have updated the readme. I forgot the integration has been added to the default HACS store. So no custom repositories is needed.
