### ISSUE TITLE
Does this plugin support multiple "Draadloze slimme hubs" active at the same time?

### ISSUE THREAD

**Issue by yannicklips** [joleys/niko-home-control-II#106]
First of all, thank you for your great work on this plugin!

A question for a larger property with a detached work shed at the far end of the plot. The Niko Home Control for existing cabling works great in the main house and all devices connect to the "Draadloze slimme hub voor bestaande bekabeling". Niko Home Control Zigbee devices installed in the shed cannot reach the main house though.

I am ok to purchase an additional "Draadloze slimme hub voor bestaande bekabeling" and install it in the shed with an existing wired network connection back to the main house, but will this Home Assistant plugin support multiple hubs active at the same? I would assume as the interface shows "Add hub" below my existing one, but wanted to make sure before buying hardware.

Thanks!

**Comment by tijsverkoyen** [comment]
@yannicklips that is a good question. 
In theory that should work by adding multiple hubs in the integration. But I did not test this.

**Comment by tijsverkoyen** [comment]
@yannicklips do you expect something from me at this point? If so: feel free to reopen the issue.

**Comment by yannicklips** [comment]
No thank you very much. When the shed is being fitted out, I’ll test and report back.Op 5 jan 2024 om 15:39 heeft Tijs Verkoyen ***@***.***> het volgende geschreven:﻿
@yannicklips do you expect something from me at this point? If so: feel free to reopen the issue.
