### ISSUE TITLE
Unable to turn on/off daikin AC (generic AC) via Niko integration

### ISSUE THREAD

**Issue by ostracon** [joleys/niko-home-control-II#107]
Hi,

This integration is working pretty well for my use case, appreciate all the work that's gone into it!

I have some Daikin AC units integrated into my Niko installation, and was hoping to control them via HA (especially as I cannot do this with the newer Daikin control methods now). They appear in the Home Control programming software as generic units, which I guess most closely correspond to "NHC HVAC Thermostat" mentioned in the README, which I realise is untested! 

I can correctly read state information from the devices, and set the temperate, but the other functionality - particuarly turning the units on and off, does not work.

I realise this is untested, I'm happy to try to test things out in the Python code, but am a newcomer to HA in general so unsure of where to start.

I'm not sure if this related but I get a lot of errors along the lines of:
```Logger: custom_components.nhc2.nhccoco.coco
Source: custom_components/nhc2/nhccoco/coco.py:158
Integration: Niko Home Control II ([documentation](https://github.com/joleys/niko-home-control-II/blob/master/README.md), [issues](https://github.com/joleys/niko-home-control-II/issues))
First occurred: 8 January 2024 at 21:44:06 (8560 occurrences)
Last logged: 21:30:36

'NoneType' object has no attribute 'loop'
```

in my logs; when I enabled debug logging and do a service call along the lines of:

```
service: climate.turn_on
data: {}
target:
  entity_id: climate.daikinap61769
```

I see a log item like:

```
2024-01-09 21:33:18.390 DEBUG (Thread-2 (_publish_device_control_commands)) [custom_components.nhc2.nhccoco.coco] → Publishing device control command: {"Method": "devices.control", "Params": [{"Devices": [{"Uuid": "7b03c01f-2947-42cd-a063-12677ff630c5", "Properties": [{"OperationMode": "Auto"}]}]}]}
2024-01-09 21:33:19.299 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.devices.controller] Controller changed (hobby/control/devices/evt == /control/devices/rsp).
2024-01-09 21:33:19.305 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.devices.generic_hvac] DaikinAP61769 changed. Topic: hobby/control/devices/evt | Data: {'Uuid': '7b03c01f-2947-42cd-a063-12677ff630c5', 'Properties': [{'OperationMode': 'Auto'}]}
```

If I change the mode to something else in the Niko app (e.g. 'Heat'), running this call does change the mode back to 'Auto' as you might expect from the log, but doesn't turn it on. Simiarly, calling `climate.set_hvac_mode` appears to work, but wont' power the unit on.

In the Niko app, the controls are:
Setpoint temperature
Program (e.g. Manual/Schedule/Holiday)
Fan speed
Operation mode
Power

It seems only the last one is missing from the integration here. Happy to test/provide more info as needed!

**Comment by tijsverkoyen** [comment]
> I have some Daikin AC units integrated into my Niko installation, and was hoping to control them via HA (especially as I cannot do this with the newer Daikin control methods now). They appear in the Home Control programming software as generic units, which I guess most closely correspond to "NHC HVAC Thermostat" mentioned in the README, which I realise is untested!

I don't think they will be seen as a NHC HVAC Thermostat. But probably as [Generic Heating/Cooling Implementation](https://github.com/joleys/niko-home-control-II#generic-heatingcooling-implementation). To be sure you can check Settings → Devices & Services → Niko Home Control II → XX devices. Search for the device, and check the model.

> I can correctly read state information from the devices, and set the temperate, but the other functionality - particuarly turning the units on and off, does not work.

Probably Daikin exposes some properties that are not documented. If you can provide me with a device list I can try to add better support. See https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list

> I'm not sure if this related but I get a lot of errors along the lines of:
> 
> Source: custom_components/nhc2/nhccoco/coco.py:158
> Integration: Niko Home Control II ([documentation](https://github.com/joleys/niko-home-control-II/blob/master/README.md), [issues](https://github.com/joleys/niko-home-control-II/issues))
> First occurred: 8 January 2024 at 21:44:06 (8560 occurrences)
> Last logged: 21:30:36
> 
> 'NoneType' object has no attribute 'loop'
> in my logs; when I enabled debug logging and do a service call along the lines of:

To my knowledge this is related to the Niko Controller restarting. 

> In the Niko app, the controls are:
> * Setpoint temperature
> * Program (e.g. Manual/Schedule/Holiday)
> * Fan speed
> * Operation mode
> * Power
> 
> It seems only the last one is missing from the integration here. Happy to test/provide more info as needed!

With the device list I will be able to see this.

**Comment by tijsverkoyen** [comment]
@ostracon I just took a quick look:

*  There is no property Power exposed. So that is not the issue. 
* Alle exposed properties are implemented. 

I think https://github.com/joleys/niko-home-control-II/pull/108 should resolve the issue. Can you try to apply the changes on your local installation. After applying the changes you will need to restart Home Assistant.

Can you also test this. As I don't have a Daikin AC ;-)

**Comment by ostracon** [comment]
Thanks - I'll try this now.

I had already hacked the same file a little to add the following:
```
    async def async_turn_on(self) -> None:
        self._device.set_status(self._gateway, PROPERTY_STATUS_VALUE_ON)
        self.on_change()
        
    async def async_turn_off(self) -> None:
        self._device.set_status(self._gateway, PROPERTY_STATUS_VALUE_OFF)
        self.on_change()
```

With that, I could turn on the device by calling the service `climate.turn_on` from developer tools, but turn_off was not working.

With this, and your fix, I can see similar behaviour - the AC will turn on when it is off and I set the mode to 'Auto', etc., but will not sure off either if I call turn_off or through the UI.

FWIW, if I try to change the fan speed from the UI, I also see "Fan mode is not valid. Valid fan modes are: off, low, medium, high, auto."

**Comment by ostracon** [comment]
Thanks for the hints on this - the linked PR fixes this, and I get the full functionality available now.  :)

![Screenshot 2024-01-10 at 21 45 44](https://github.com/joleys/niko-home-control-II/assets/2281593/0ba203ca-a62a-4b53-b0e3-78348eb88d7b)

**Comment by tijsverkoyen** [comment]
@ostracon big thank for your effort!
I have released https://github.com/joleys/niko-home-control-II/releases/tag/v3.3.3 which includes your changes
