### ISSUE TITLE
Energy tab on the Niko touch screen 

### ISSUE THREAD

**Issue by flimofly** [joleys/niko-home-control-II#112]
When using a Niko touch screen profile to connect to Home Assistant, energy-related information is transferred to Home Assistant, but the Energy tab on the touch screen itself does not display any information.

Error on the touch screen display: "no energy modules in your Niko Home Control installation"

Tried to fix by switching off the energy toggle in the Niko Home Control programming software > touch screen profile. The energy-related entities in Home Assistant then become unavailable. Yet, after switching the toggle back on, the energy tab on the touch screen is still not populated.

**Comment by tijsverkoyen** [comment]
@flimofly any news?

**Comment by flimofly** [comment]
Received word from Niko that the touch screen only displays energy info from the NHC energy modules, not from a P1 port on the digital energy meter connected to the Niko wireless bridge.

**Comment by tijsverkoyen** [comment]
Ok, so this issue can be closed?

**Comment by flimofly** [comment]
Yes!
