### ISSUE TITLE
Electricity value not updating

### ISSUE THREAD

**Issue by Roeli1996** [joleys/niko-home-control-II#116]
Good morning

My electricity consumption has not been updated in Home Assistant for a while now. The values in the Niko Home App and on the touchscreen appear to be correct. I use a wireless bridge which is connected to my digital P1 meter.

Everything is on the latest version.

Kind regards
Arne

**Comment by tijsverkoyen** [comment]
@Roeli1996 Can you explain which entity/device you are talking about?

**Comment by Roeli1996** [comment]
Good afternoon Tijs

My apologies. I use the 'Niko Home Control 2 integration' on Home Assistant:
- NHC2 integration: 3.3.3
- Core: 2024.1.5
- Supervisor: 2023.12.1

I used to use Generci (Energyhome):
- sensor.energyhome_electrical_power_from_grid
- sensor.energyhome_electrical_power_to_grid

These two entities have been frozen for a number of days and weeks now.
My P1 port of my digital electricity meter is connected to a Niko - Wireless bridge (550-00640) which is connected to an NHC2 controller. This setup has worked for a long time without any problems. I suspect the errors started since the last integration update.

For your information:
I also have the following messages in my logging:
`Logger: homeassistant.setup
Source: setup.py:403
First occurred: 28 januari 2024 om 14:32:52 (4 occurrences)
Last logged: 07:42:09

Unable to prepare setup for platform 'nhc2.binary_sensor': Platform not found (No module named 'custom_components.nhc2.entities.overallcomfort_action_start_active').
`

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.nhc2.nhccoco.coco
Source: custom_components/nhc2/nhccoco/coco.py:296
Integration: Niko Home Control II (documentation, issues)
First occurred: 28 januari 2024 om 14:32:52 (32 occurrences)
Last logged: 07:42:09

Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Geen actieve beweging.'}]
Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Laag.'}]
Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Sirene staat uit.'}]
Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Geen beweging.'}]
Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'On'}, {'FeedbackMessage': 'Beweging.'}]`


`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.nhc2.nhccoco.coco
Source: custom_components/nhc2/nhccoco/coco.py:199
Integration: Niko Home Control II (documentation, issues)
First occurred: 03:17:22 (6 occurrences)
Last logged: 07:40:49

Disconnected from MQTT broker`

**Comment by tijsverkoyen** [comment]
> For your information:
> I also have the following messages in my logging:
> ````
> Logger: homeassistant.setup
> Source: setup.py:403
> First occurred: 28 januari 2024 om 14:32:52 (4 occurrences)
> Last logged: 07:42:09
> 
> Unable to prepare setup for platform 'nhc2.binary_sensor': Platform not found (No module named 'custom_components.nhc2.entities.overallcomfort_action_start_active').
> `
> 
> `Deze fout is ontstaan door een aangepaste integratie.
> 
> 
> Logger: custom_components.nhc2.nhccoco.coco
> Source: custom_components/nhc2/nhccoco/coco.py:296
> Integration: Niko Home Control II (documentation, issues)
> First occurred: 28 januari 2024 om 14:32:52 (32 occurrences)
> Last logged: 07:42:09
> 
> Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Geen actieve beweging.'}]
> Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Laag.'}]
> Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Sirene staat uit.'}]
> Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'Off'}, {'FeedbackMessage': 'Geen beweging.'}]
> Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction', device: [{'BasicState': 'On'}, {'FeedbackMessage': 'Beweging.'}]`
> 
> `Deze fout is ontstaan door een aangepaste integratie.
> 
> Logger: custom_components.nhc2.nhccoco.coco
> Source: custom_components/nhc2/nhccoco/coco.py:199
> Integration: Niko Home Control II (documentation, issues)
> First occurred: 03:17:22 (6 occurrences)
> Last logged: 07:40:49
> 
> Disconnected from MQTT broker`
> ````

The errors will be resolved once https://github.com/joleys/niko-home-control-II/pull/110 is merged.
I will try to do this later this week of I don't receive any feedback.

**Comment by tijsverkoyen** [comment]
https://github.com/joleys/niko-home-control-II/releases/tag/v4.0.0 had been released. This should resolve the lolentry for `Class CocoPlayerstatusAction not found module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoPlayerstatusAction' ...`

For the energyhome_electrical_power_from_grid not updating I don't really see anything wrong in the code. But I don't have a digital meter, so I can't test this. Could you enable debug-mode, and check for changes to the Energy Home device in the logs?

**Comment by Roeli1996** [comment]
The problem seems to be solved in the newest version. 

I think there was something wrong with the state of "energyhome_disable_report_instant_usage_re_enabling". This one wasn't updating itself anymore. 

As you can see in the picture below, in the new version the entity is updating itself. 
![Screenshot_2024-02-04-13-52-14-85_c3a231c25ed346e59462e84656a70e50](https://github.com/joleys/niko-home-control-II/assets/118668044/37f81f3e-25fe-4bf6-93ad-63ec4d1ac29d)
