### ISSUE TITLE
Lost contact with NHCII API in HA and directly?

### ISSUE THREAD

**Issue by Johndowne** [joleys/niko-home-control-II#121]
We appear to have lost all contact with the Niko API and can’t see why. We use the Hobby API directly outside HA a well as in HA so it looks like a more general Niko related issue - but has anyone else on here had a problem? Ours started 5pm Uk time yesterday.

**Comment by tijsverkoyen** [comment]
Does the Niko App on your phone still works?

**Comment by Johndowne** [comment]
Yes App is fine

**Comment by tijsverkoyen** [comment]
> We use the Hobby API directly outside HA a well as in HA so it looks like a more general Niko related issue 

And that other thing is working? If not: are you sure the Hobby API token is not expired. It has a lifetime of 1 year if I remember correctly. If it is not expired: I would suggest to contact Niko directly.

**Comment by Johndowne** [comment]
No our direct use of the Hobby API has stopped working as well. 

Yes we have renewed the API token a few weeks ago. In the HA/ NHC files I can’t find where the API KEY / username etc are stored. Could you remind me where I should be able to find those details?

it would be useful to know if any other HA/NHCII user has experienced any issues like this?

I agree we will try to contact Niko ( not so easy though!)

**Comment by Johndowne** [comment]
Trying to do that I think I've screwed up my HA installation!

**Comment by tijsverkoyen** [comment]
You can unpack a backup and compare the files? Or just restore the backup.
I guess it will be invalid JSON, so you use https://jsonlint.com to see where there is an issue.

**Comment by Johndowne** [comment]
Phew - 1. I have our HA back running and 2. NHCII integration is now working. Very strange as it is running with what should be the previous API key. I think the IP address of the Niko device was wrong for some reason (now static!).
Thanks for your help

**Comment by tijsverkoyen** [comment]
From what I heard, but not 100% verified. Is that the Hobby API key is only checked when the controller is restarted. So it could be that if you restart the controller the "old" key will be invalid.

**Comment by user152306** [comment]
> From what I heard, but not 100% verified. Is that the Hobby API key is only checked when the controller is restarted. So it could be that if you restart the controller the "old" key will be invalid.

I can "verify" that, I only needed to update my HobbyAPI-key after the Niko Controller restarted after a power outage. I was running 2 months on an expired API-key before the power-outage, and I had HA-restarts ruing that time.
