### ISSUE TITLE
ClimateEntityFeature

### ISSUE THREAD

**Issue by tijsverkoyen** [joleys/niko-home-control-II#123]
Check if we need to do something with https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

**Comment by blatruwe** [comment]
This might be related?

`2024-02-09 14:23:35.192 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.nhc2.entities.thermostat_thermostat_climate.Nhc2ThermostatThermostatClimateEntity'>) implements HVACMode(s): auto, heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/joleys/niko-home-control-II/issues`
