### ISSUE TITLE
Duco ventilation unit notifications via Niko

### ISSUE THREAD

**Issue by hazcod** [joleys/niko-home-control-II#124]
Hi there,

Perhaps an odd one, but I have the Niko Hub integrated into Home Assistant, which feeds into Homekit.
My Ducobox Focus ventilation unit is connected officially to my Niko installation, which then feeds these entities into Home Assistant, and thus to HomeKit.

The duco ventilation monitors CO2 levels in my rooms. Every morning the CO2 levels spike for a specific room, which should trigger the Duco to up the air suction for that room to lower it. However, this always generates a CO2 warning push notification via Niko, and thus to HomeKit. 

Is there a way to mute this notification in this integration? Does it pass notifcations at all?
 I'm not 100% sure where to look.
Thank you.

![image](https://github.com/joleys/niko-home-control-II/assets/5222512/2904219a-dc89-4e62-bf54-ec4296a145ea)

**Comment by tijsverkoyen** [comment]
What do you mean by a "notification"? A push notification in the Niko Home Control app on your phone? 
The integration only updates entities. There is nothing in there that sends notifications.

**Comment by hazcod** [comment]
Interesting, the search continues in that case. It's a push notification in HomeKit itself, maybe hassio sets a default CO2 treshold for CO2 sensors. Thanks!

**Comment by joleys** [comment]
The notification originates with HomeKit.  I encountered the same in my setup (with eCO2 reading coming from an ESP).  The only solution for me was the explicitly remove the sensor from the HomeKit integration in the configuration.yaml, but then of course there is no reading at all.
