### ISSUE TITLE
Class CocoSolarmodeAction not found

### ISSUE THREAD

**Issue by Gavergracht** [joleys/niko-home-control-II#127]
Warning in log ...

Class CocoSolarmodeAction not found: module 'custom_components.nhc2.nhccoco.coco' has no attribute 'CocoSolarmodeAction', device: [{'BasicState': 'On'}]

**Comment by tijsverkoyen** [comment]
Can you email me your device list?
See https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list

**Comment by Gavergracht** [comment]
I only have a cover and a switch running

update.home_control_ii_latest_controller_config

switch.slimme_stekker_zigbee_r_garage

cover.zonwering_keuken
binary_sensor.zonwering_keuken_aligned
sensor.zonwering_keuken_last_direction
binary_sensor.zonwering_keuken_moving

**Comment by tijsverkoyen** [comment]
The error indicates you have another device "Solarmode Action" that is not (yet) supported by this integration.
With the device list I can try to implement it.

**Comment by tijsverkoyen** [comment]
@Gavergracht any news?

**Comment by Gavergracht** [comment]
Sorry, but I didn't had much time to check my HA. it has been to busy lately.

**Comment by tijsverkoyen** [comment]
@Gavergracht any update?
Or can I close this issue?

**Comment by Gavergracht** [comment]
You can close it ...Op 16 apr. 2024 16:49 schreef Tijs Verkoyen ***@***.***>:
@Gavergracht any update?
Or can I close this issue?
