### ISSUE TITLE
Action shows "off" state even when on

### ISSUE THREAD

**Issue by debietim** [joleys/niko-home-control-II#132]
When I start an action in Niko Home Control via the devices list in Home Assistant the linked device turns on, but after a few seconds (5) in Home Assistant the device shows the "off" status, while the device stays on.
To shut it down, I need to turn it on again in Home Assistant and then switch it off in the seconds before it's been shown in the off state in Home Assistant. Is there a fix for this?

**Comment by tijsverkoyen** [comment]
@debietim I suspect you are talking about the Mood actions? Can you tell me which entity is switching off after 5 seconds. Because I think you are using the Mood Active Binary Sensor, and that will change to off when a participant in the Mood action has a state change.

**Comment by debietim** [comment]
@tijsverkoyen It is a basic action in Niko Home Control that controls a light. But I have it with dimmed lamps and other switched actions as well (no moods)
<img width="1154" alt="Screenshot 2024-04-04 at 18 25 13" src="https://github.com/joleys/niko-home-control-II/assets/106590109/f309f61a-5bb9-4814-a5bb-5c9b5e53b0c7">

**Comment by tijsverkoyen** [comment]
Weird. I have also lights and dimmers and do not have this behaviour.

Some questions:

1. Which version of this integration do you have installed? 
2. And which version of Niko Home Control?
3. Can you enable debug logging for this integration and check if the states changes are shown in the log files?
4. Do the lights actually change? As in if you switch off the light through Home Assistant, does it switch off in the real world?

**Comment by tijsverkoyen** [comment]
@debietim any update?

**Comment by tijsverkoyen** [comment]
@debietim I will close this issue as you did not respond. Feel free to reopen the issue if needed.
