### ISSUE TITLE
Setting up the Energy-tab (electricity consumption and production) by using the NHC2 Electricity clamps

### ISSUE THREAD

**Issue by roelteeuwenNL** [joleys/niko-home-control-II#133]
Hi,

First of all I really want to thank @tijsverkoyen for all the hard and excellent work. I'm building up my NHC2 Home Assistant setup bit for bit. 

I've a question. Currently I've 3 NHC2 Electricity-Clamps all visible in HAS:
1. Driefasige elektriciteitsmeting Totaal (showing the total electricity power consumption / flow: consumer)
2. Driefasige elektriciteitsmeting Warmtepomp (it's a seperate subsegment clamp on my heatpump / flow: consumer)
3. Driefasige elektriciteitsmeting Teruglevering ZonPV (it's a seperate subsegment clamp on my solar panel inverter / flow: producer)

When I try to setup the Energy configuration within HAS and want to add consumption or production in the firt pull-down menu the clamps are not showing so I cannot configure the "Netconsumption configuration" and the "Netproduction configuration" 

Is it possible to configure the HAS electricitynet option for consumption and production with the clamps?

Best regard and thanks 
Roel

**Comment by J13K13** [comment]
Op za 13 apr. 2024 22:33 schreef tRoOlos ***@***.***>:

**Comment by tijsverkoyen** [comment]
I think the Energy Dashboard expects the totals to be in Wh and the clamp is reporting in W. 
You can see https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#calculated-totals to convert

**Comment by tijsverkoyen** [comment]
@roelteeuwenNL I will close this issue as there is no feedback. Feel free to reopen it if needed.

**Comment by roelteeuwenNL** [comment]
@tijsverkoyen thanks!!, I didn't have time to test it, but I'll let it know if I cannot get it to work. 👍

**Comment by roelteeuwenNL** [comment]
Hi @tijsverkoyen, excellent! That did the trick (sorry for the late respons ;).
