### ISSUE TITLE
No entities shown for niko

### ISSUE THREAD

**Issue by wvdb0** [joleys/niko-home-control-II#141]
Since the last update of ha i lost at first the abillity to control my niko plug and switch. Then it no longer shows the entities. I tried reinstalling the plugin. Removed it. Installed the last version. Nothing works.

**Comment by tijsverkoyen** [comment]
Are you 100% sure you have v4.0.2 installed?
Can you enable logging and check the logs for any errors.

**Comment by wvdb0** [comment]
[error_log-56.txt](https://github.com/joleys/niko-home-control-II/files/15197313/error_log-56.txt)
It is 4.0.2
![Screenshot_20240503_094253_Home Assistant](https://github.com/joleys/niko-home-control-II/assets/128087532/510b8ab4-0d8f-4890-b5f8-cf931ab13ef1)

**Comment by 60rdm** [comment]
Same problem here. Log attached (partial).
[Niko_HA_fout.txt](https://github.com/joleys/niko-home-control-II/files/15198250/Niko_HA_fout.txt)

**Comment by tijsverkoyen** [comment]
Could one of you try with the changes of https://github.com/joleys/niko-home-control-II/pull/140
I don't have access to my Niko installation today

**Comment by ubipo** [comment]
These were the same symptoms I got, #140 should indeed fix it. I don't see the same error in the attached log though.

**Comment by Johndowne** [comment]
Just realised my issue was new router had caused different IP address for NHC2.

Removed Integration and re-setup with new IP and Password / Hobby API code which was all accepted.

However no devices / sensors etc have been discovered? Surely they should all just appear or am I being thick?

**Comment by homeassistrobbie** [comment]
I lost all my entities in NHC2 too, 2 days ago.  System wasn't doing anything.  

removing and adding the integration doesn't fix it.  I tried a touchscreen profile and the api key method.

**Comment by tijsverkoyen** [comment]
@wvdb0 , @60rdm , @Johndowne or @homeassistrobbie can you try to apply the changes in #140 and confirm this solves the issue?

**Comment by wvdb0** [comment]
As soon  as i get home i will try it.

**Comment by homeassistrobbie** [comment]
I'm a programmer in training (just started) and have honestly no idea how to optain or apply the patch....

**Comment by Johndowne** [comment]
I have no updates to HA integration outstanding and am on 4.0.2 already.
Not sure how to try #140

**Comment by 60rdm** [comment]
@tijsverkoyen , tested your changes from #140 and it now works fine, all entities and devices are loaded/detected again.
Thank you very much!

**Comment by tijsverkoyen** [comment]
> @tijsverkoyen , tested your changes from #140 and it now works fine, all entities and devices are loaded/detected again. Thank you very much!

Thanks for confirming. All the work was done by @ubipo. So big thanks to @ubipo

I have created [v4.1.0](https://github.com/joleys/niko-home-control-II/releases/tag/v4.1.0) which includes this fix.

**Comment by wvdb0** [comment]
Allright i was just trying it got the update and it all works again! Thanks for the fast update

**Comment by Johndowne** [comment]
Updated and all resolved thanks!

**Comment by homeassistrobbie** [comment]
Entities are back! Thnx for the great work you guys put in here !
