### ISSUE TITLE
Sensor switch: sensors Unavailable

### ISSUE THREAD

**Issue by 2azure** [joleys/niko-home-control-II#144]
I have 5 sensor switches, but the sensors are not working. The switch it self does work. output in Home assistant:

Sensors
Ambient Temperature       Unavailable
Heat Index                         Unavailable
Humidity                           Unavailable

If you need access to troubleshoot or need my help let me know.

**Comment by tijsverkoyen** [comment]
Can you share a screenshot?
Or explain which Niko devices you are using?
Or share a device list?

**Comment by Alexandersen50** [comment]
I also have some sensors that don't work anymore.
it says:
NIKO Electrical Power Consumption aren't supplied from the nhc2 integration anymore

**Comment by tijsverkoyen** [comment]
> I also have some sensors that don't work anymore. it says: NIKO Electrical Power Consumption aren't supplied from the nhc2 integration anymore

Could it be that there is a new `Electrical Energy Consumption` sensor with that information?

**Comment by 2azure** [comment]
![image](https://github.com/joleys/niko-home-control-II/assets/53003664/f3220092-385b-47a9-829c-bfa14c41f83e)

I am using Nike Drukknop met Comfortsensoren, single and double.

**Comment by tijsverkoyen** [comment]
@2azure can you provide me with your device list. See https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list

**Comment by 2azure** [comment]
yes, send by email

**Comment by tijsverkoyen** [comment]
@2azure thx. I have check your device list. It seems like reporting HeatIndex, AmbientTemerapture and Humidity is disabled.

For example, below is the data for "Enkelvoudige drukknop met led en comfortsensoren Kelder":

````
{
          'Uuid': 'XXX`,
          'Identifier': XXX',
          'Model': 'thermoswitchx1feedback',
          'Online': 'True',
          'Name': 'Enkelvoudige drukknop met led en comfortsensoren Kelder',
          'Technology': 'nikohomecontrol',
          'Type': 'multisensor',
          'Traits': [
            {
              'MacAddress': 'XXX'
            }
          ],
          'Parameters': [
            {
              'TemperatureCalibrationOffset': '0.00'
            },
            {
              'LongPressTime01': '1000.00'
            },
            {
              'HumidityReporting': 'Disabled'
            },
            {
              'LocationName': 'Kelder'
            },
            {
              'ButtonMode01': 'ShortPress'
            },
            {
              'LocationIcon': 'basement'
            },
            {
              'HeatIndexReporting': 'Disabled'
            },
            {
              'AmbientTemperatureReporting': 'Disabled'
            },
            {
              'LocationId': 'e419a982-85dd-4839-902b-081dbddd75ea'
            }
          ],
          'Properties': [
            {
              'AmbientTemperature': ''
            },
            {
              'HeatIndex': ''
            },
            {
              'Humidity': ''
            }
          ],
          'PropertyDefinitions': [
            {
              'AmbientTemperature': {
                'HasStatus': 'true',
                'CanControl': 'false',
                'Description': 'Range(-10.00,45.00,0.50)'
              }
            },
            {
              'HeatIndex': {
                'HasStatus': 'true',
                'CanControl': 'false',
                'Description': 'Range(13.00,45.00,1.00)'
              }
            },
            {
              'Humidity': {
                'HasStatus': 'true',
                'CanControl': 'false',
                'Description': 'Range(0.00,100.00,0.10)'
              }
            }
          ]
        },
````

As you can see the following parameters have `Disabled` set as their value:

* Parameters→HumidityReporting
* Parameters→HeatIndexReporting
* Parameters→AmbientTemperatureReporting

I will create a release that handles this better and will not add the sensors when they are disabled.

**Comment by 2azure** [comment]
Hi, Thanks.

They are enabled in the software. But I noticed in the niko documentation that they will be receive new states en features in the next release. So maybe wait a bit longer for the next release?

________________________________

**Comment by tijsverkoyen** [comment]
I have released https://github.com/joleys/niko-home-control-II/releases/tag/v4.2.0

When the `HeatIndexReporting`, `AmbientTemperatureReporting`, `HumidityReporting` Parameter is present and the value is `Disabled` the relevant sensor will not be added.
