### ISSUE TITLE
Typo in nl.json in v4.3.0

### ISSUE THREAD

**Issue by blatruwe** [joleys/niko-home-control-II#157]
`homeassistant.exceptions.HomeAssistantError: Error while loading /home/homeassistant/.homeassistant/custom_components/nhc2/translations/nl.json: trailing comma is not allowed: line 31 column 6 (char 1537)`

removing the comma after `"no_controller_found": "Geen controller gevonden."` resolves the issue

**Comment by blatruwe** [comment]
see #158

**Comment by tijsverkoyen** [comment]
Nice, merged and released https://github.com/joleys/niko-home-control-II/releases/tag/v4.3.1
