### ISSUE TITLE
Add support for zigbee measurmants from smart socket

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#16]
Do you know if the connected sockets energy can be read by the api?

I have some of these in my home and want them to my home assistant as well.

**Comment by tijsverkoyen** [comment]
+1, I would really like this too. 

It is possible to retrieve the realtime readings over MQTT. But not for the totals. I have contacted Niko about this, but did not received an answer yet.

**Comment by tijsverkoyen** [comment]
@joleys I think this issue can be closed.
