### ISSUE TITLE
Device "skipped" in logs

### ISSUE THREAD

**Issue by flimofly** [joleys/niko-home-control-II#160]
NHC Installation: Controller software version: 2.20.2.613
NHC2 integration v4.3.2

I keep having issues with the door lock entity (part of the external video door unit https://www.niko.eu/en/products/niko-home-control/ip-products/external-video-unit-productmodel-niko-9d1cdb0b-fada-4f48-ac40-1d796d583578/550-22011)  

It's currently available only as an unnamed entity without a unique identifier (whereas the integration used to assign it a unique ID before).

In the logs, the device is visible:

`
{'Uuid': '8c2b48f0-7c8b-414e-b981-35e4d0a7811c', 'Identifier': '90c3b63c-27e7-4526-92ff-5549436214bd', 'Model': 'doorlock', 'Online': 'True', 'Name': 'Voordeur slot', 'Technology': 'nikohomecontrol', 'Type': 'lock', 'Traits': [{'Channel': '0'}, {'MacAddress': '0078cc4f'}], 'Parameters': [{'LocationName': 'Home'}, {'LocationId': '674631d1-8c0b-4a88-a7d6-f42cc454de9e'}, {'LocationIcon': 'general'}], 'Properties': [], 'PropertyDefinitions': []}
`

However, the device is `skipped` by the NHC2 integration in HASS:
`
2024-06-16 11:30:39.554 DEBUG (Thread-3 (_thread_main)) [custom_components.nhc2.nhccoco.coco] Skipping 8c2b48f0-7c8b-414e-b981-35e4d0a7811c of CocoDoorlockLock
`

Any ideas why it is skipped?

**Comment by joleys** [comment]
The Doorlock itself does not expose any Properties.  It should be under 'accesscontrol'.
I don't have a doorlock in my installation but just wonder if you can create a second routine that uses the same output?

**Comment by flimofly** [comment]
In the programming software only one routine can be linked to the external video unit at any given time.  I created a new one but it has to the same problem. The sensors (call pending, call answered, decline call on all devices) are available under `accesscontrol` but the door lock isn't.

**Comment by flimofly** [comment]
Removing the video unit, the routine and the door lock and adding them again makes no difference.

**Comment by tijsverkoyen** [comment]
@flimofly can you send me your device list? Then I will try to give it a look. But no promises on when. I suspect that because the doorlock is linked to multiple devices the entity does not have a unique name and therefore is not created.

**Comment by flimofly** [comment]
Thanks, here you go: 
[devicelist.log](https://github.com/user-attachments/files/15877497/devicelist.log)

**Comment by tijsverkoyen** [comment]
@flimofly can you check if there is a unnamed Lock in the list of entities, and if that works?
A fix to link it to the correct device is available in https://github.com/joleys/niko-home-control-II/pull/161

But can you confirm this works.

**Comment by flimofly** [comment]
`lock.unnamed_device` works. I can't see it in the entities list now, but I can use it in an automation.

**Comment by tijsverkoyen** [comment]
Ok, good to know. 
I will merge the PR and create a release

**Comment by tijsverkoyen** [comment]
I have release [v4.3.3](https://github.com/joleys/niko-home-control-II/releases/tag/v4.3.3) which includes the fix.
