### ISSUE TITLE
Alarm entities unavailable

### ISSUE THREAD

**Issue by dsvdglenn** [joleys/niko-home-control-II#162]
When I upgrade the plugin from 4.2.0 to 4.3.1 my alarm entities from Niko becomes unavailable.
The main entity is missing -> alarm_control_panel.ENTITY
Current version HA: 2024.6.3

If you need extra info, shoot! ;-)

Thanks in advance

**Comment by tijsverkoyen** [comment]
Can you send me your device list please. See https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list

**Comment by dsvdglenn** [comment]
Hello Tijs, I have sent you an e-mail with the device list.

Thanks!

**Comment by tijsverkoyen** [comment]
@dsvdglenn could you apply https://github.com/joleys/niko-home-control-II/pull/163 and check if the Alarm Control Panels are back?

**Comment by dsvdglenn** [comment]
@tijsverkoyen Top, het werkt!

**Comment by tijsverkoyen** [comment]
I have release [v4.3.3](https://github.com/joleys/niko-home-control-II/releases/tag/v4.3.3) which includes the fix.
