### ISSUE TITLE
Error on clean install of latest HA OS

### ISSUE THREAD

**Issue by minosrex** [joleys/niko-home-control-II#166]
Hi. I just installed the latest version of HA OS (2024.6.3), and copied over the settings from a running container version (2024.6.0). 

I however get the following error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nhc2_backup_2/__init__.py", line 134, in async_setup_entry
    dev_reg = hass.helpers.device_registry.async_get(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given

NHC2 still runs fine in the containered version. What could be the issue?

**Comment by joleys** [comment]
Are you using the latest version of the integration?

**Comment by minosrex** [comment]
Yes: version": "v4.3.4"

**Comment by tijsverkoyen** [comment]
Is there a reason why the component is installed in `/config/custom_components/nhc2_backup_2`? Could it be that this is a backup that should not be used?

**Comment by tijsverkoyen** [comment]
@minosrex as there is no response from you I will close this issue.
Feel free to reopen it if you think this is not correct.
