### ISSUE TITLE
Gas Consumption

### ISSUE THREAD

**Issue by knownsolution** [joleys/niko-home-control-II#167]
With the belgium digital meters, we are able to read via niko home control 2 hub and a connection with the digital meter via a P2 cable the electric consumption but also the gas consumption. i try to see in the entities in home assistant but i don't seem to find this.
hope you can find in future updates the time to find this.

**Comment by tijsverkoyen** [comment]
I think this is a duplicate of https://github.com/joleys/niko-home-control-II/discussions/120

I don't (yet) have a digital meter myself so I can't see if the data is already available through the API, but I don't think so.

Would you be so kind to check your [device list](https://github.com/joleys/niko-home-control-II?tab=readme-ov-file#i-need-to-see-the-device-list) and check if the data is present the JSON? If so: feel free to send over de device list and I will check if I can implement it.

**Comment by tijsverkoyen** [comment]
As there is no response I will close this issue.
