### ISSUE TITLE
Detected integration that uses deprecated `async_get_registry` - simple edit needed.

### ISSUE THREAD

**Issue by NickInManchester** [joleys/niko-home-control-II#17]
I'm never quite sure where the right place to report things is. But on HA startrup I'm getting a log warning. Looking at the Pythin code it is obvious what needs a minor edit right at the end of the __initi__.py file. If this is the wrong place, please do me a favour and forward it to the correct person:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 10:22:08 AM (1 occurrences)
Last logged: 10:22:08 AM

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for nhc2 using this method at custom_components/nhc2/__init__.py, line 118: dev_reg = await hass.helpers.device_registry.async_get_registry()

    hass.data.setdefault(KEY_GATEWAY, {})[entry.entry_id] = coco
    hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, on_hass_stop)

    _LOGGER.debug('Connecting to %s with %s',
                  entry.data[CONF_HOST], entry.data[CONF_USERNAME]
                  )
    coco.connect()
    **dev_reg = await hass.helpers.device_registry.async_get_registry()**
    coco.get_systeminfo(get_process_sysinfo(dev_reg))

    return True

**Comment by joleys** [comment]
Fixed.

**Comment by NickInManchester** [comment]
Thank you!
