### ISSUE TITLE
Renew hobby token

### ISSUE THREAD

**Issue by hazcod** [joleys/niko-home-control-II#176]
Hi!

Thank you for this integration.
Is there some documentation available on how to renew the hobby token in the HA integration, except for waiting until it breaks on the old token? Couldn't immediately find it.

Thanks!

**Comment by tijsverkoyen** [comment]
The integration will show a warning when the token is not accepted anymore by the controller.

If you really need to change it manually you can edit it in the config_entries. But make sure you know what you are doing if you are altering Home Assistant files directly.
