### ISSUE TITLE
Niko Home Control HUB probleem

### ISSUE THREAD

**Issue by DenBenny87** [joleys/niko-home-control-II#183]
Hey,

Ik heb 2 installaties van Niko Home Control die beide werkende waren op Home Assistant.
Nu na werken aan mijn netwerk en veranderen van IP's van niko home control heb ik de integratie opnieuw moeten installeren in HA,
Maar ik krijg geen 2 hubs van NHC geïnstalleerd. ik krijg steeds de melding "Niko Home Control II
Deze controller en profiel zijn reeds toegevoegd. Je kan deze geen 2 keer toevoegen."
De 2 installaties zijn met verschillende API sleutels zoals voorheen... enkel de ip adressen zijn aangepast.
hoe zou ik dit kunnen oplossen?

mvg Benny

**Comment by DenBenny87** [comment]
Hey,

misschien nog iets toevoegen...
Als ik de 1ne HUB verwijder en de andere toevoeg werkt die wel... maar beide in HA werkt niet...

**Comment by tijsverkoyen** [comment]
Do you use hobby for both? If so can you try with touch profiles with a different name

**Comment by tijsverkoyen** [comment]
Euh, in the integration there is no difference between hobby and touchprofiles. So it should be something related to the settings in the controller / touch profiles. 

I would suggest to double check the profiles and make sure it is uploaded to the controller. If that does not resolve it, you should contact Niko support.

**Comment by tijsverkoyen** [comment]
@DenBenny87 any feedback? Can this issue be closed?

**Comment by DenBenny87** [comment]
Hey Tijs,
I now use it as you said with the touchscreen profiles and that works... yet I have a few entities somewhere that I miss compared to the hobby.

thanks again for the help!
