### ISSUE TITLE
Duco boost switches disappeared

### ISSUE THREAD

**Issue by hazcod** [joleys/niko-home-control-II#190]
Hi,

I have a ducobox ventilation integration setup within Niko Home Assistant.
One of the features is enabling 'boost', aka a temporary increase of the fan speed.
This works in the Niko application.

For some reason, the boost entities no longer exist.
The fans themselves do tough;
![image](https://github.com/user-attachments/assets/a3ae4ffe-9893-4974-9d16-77061da70596)

Any idea how to debug where this ended up? I don't see something immediately in the logs.
Changing fan speeds also does not seem to work but I'm unsure if this ever worked in HA.

HACS v4.5.0

**Comment by hazcod** [comment]
Hmm, maybe related:
```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 14:01:15 (12 occurrences)
Last logged: 14:01:15

Entity None (<class 'custom_components.nhc2.entities.generic_fan_fan.Nhc2GenericFanFanEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/joleys/niko-home-control-II/issues
Entity None (<class 'custom_components.nhc2.entities.generic_fan_fan.Nhc2GenericFanFanEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/joleys/niko-home-control-II/issues
```

**Comment by hazcod** [comment]
FWIW I don't see the `Received device list` log entry.

**Comment by tijsverkoyen** [comment]
That is very weird. As this would mean that your Niko Controller is not sending anything. Which should mean none of the entities is available?

**Comment by hazcod** [comment]
Any way I can assist @tijsverkoyen ?

Also saw error:
```
Logger: custom_components.nhc2.nhccoco.coco
Source: custom_components/nhc2/nhccoco/coco.py:187
integration: Niko Home Control II ([documentation](https://github.com/joleys/niko-home-control-II/blob/master/README.md), [issues](https://github.com/joleys/niko-home-control-II/issues))
First occurred: 18 November 2024 at 17:06:31 (18 occurrences)
Last logged: 08:14:57

'NoneType' object has no attribute 'loop'
Traceback (most recent call last):
  File "/config/custom_components/nhc2/nhccoco/coco.py", line 187, in _on_message
    self._device_instances[device[MQTT_DATA_PARAMS_DEVICES_UUID]].on_change(topic, device)
  File "/config/custom_components/nhc2/nhccoco/devices/device.py", line 167, in on_change
    callback()
  File "/config/custom_components/nhc2/entities/nhc_entity.py", line 21, in on_change
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1244, in schedule_update_ha_state
    self.hass.loop.call_soon_threadsafe(
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'loop'
```

**Comment by hazcod** [comment]
FWIW tried removing nico addon, restarting HA, restarting duco, no dice.
Maybe because of a niko update?

**Comment by tijsverkoyen** [comment]
I find this all weird.

1. If you have removed and readded the Niko integration, did it work? Were you able to enter your credentials without any error?
2. Does the integration has any entities that are available? Because if no device list is present it will not have any entities (available)
3. Are you 100% sure your credentials are correct.
4. If you have setup the logging to debug correctly, there should be a lot of information in the log about the Niko integration. And I suspect there is something in it that says that there can't be made a connection.

**Comment by hazcod** [comment]
Well the odd thing is, everything within Nico works. (including Duco and its boost)
All nico entities (excluding boost) is being detected in HA, and its retrieving all entities/devices (without the boost switches).
The fan controls don't work, but I didn't test that before so maybe that was always the case.

**Comment by hazcod** [comment]
If you're willing to take a live look for a coffee, let me know. :-)

**Comment by tijsverkoyen** [comment]
Drop me a mail at `niko-ha [dot] verkoyen [dot] eu`.

**Comment by hazcod** [comment]
Done.

Also saw this;
```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 13:07:00 (12 occurrences)
Last logged: 13:07:00

Entity None (<class 'custom_components.nhc2.entities.generic_fan_fan.Nhc2GenericFanFanEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/joleys/niko-home-control-II/issues
Entity None (<class 'custom_components.nhc2.entities.generic_fan_fan.Nhc2GenericFanFanEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/joleys/niko-home-control-II/issues
```

**Comment by hazcod** [comment]
Seems like a Niko issue, support email opened.
A workaround is setting the fan in HA to a `Manual` mode, e.g. `Man1` for Low or `Man3` for High (100%) boost mode.
