### ISSUE TITLE
Add garagedoor

### ISSUE THREAD

**Issue by 86hakan** [joleys/niko-home-control-II#2]
Can you add the garagedoor sensor to this integration?

**Comment by 86hakan** [comment]
It´s working perfect. Thanks

**Comment by joleys** [comment]
@86hakan: I'm working on a consolidation of shutters and garage door.  Let me test this on my installation first and if it's successful I'll post the update later this week.
Unfortunately there are no shutters in my home.  Thanks for being a tester! :)

**Comment by 86hakan** [comment]
Ok. the shutters worked in earlier version. I have the second biggest installation in sweden and working as support on Niko Sweden, so its ok to be a tester. 👍 
Thanks for your work!

**Comment by joleys** [comment]
Update is available.  Let me know if this fixes your shutters.

**Comment by 86hakan** [comment]
This fix the bugg for the shutters
