### ISSUE TITLE
Logbook warning "Detected blocking call to sleep inside the event loop"

### ISSUE THREAD

**Issue by dsvdglenn** [joleys/niko-home-control-II#22]
Version of Home assistant: 2022.8.2

Logger: homeassistant.util.async_
Source: util/async_.py:180
First occurred: 12:37:00 (2 occurrences)
Last logged: 12:37:00

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for nhc2 doing blocking calls at custom_components/nhc2/nhccoco/coco_profiles.py, line 34: sleep(0.05)

**Comment by 86hakan** [comment]
I also have this problem.

**Comment by tijsverkoyen** [comment]
This is not a real problem in my opinion. The sleep is there to wait for all the profiles to be available.

@joleys I think this issue can be closed.
