### ISSUE TITLE
Renew Hobby API

### ISSUE THREAD

**Issue by jordireusens** [joleys/niko-home-control-II#38]
What is the right procedure to reconnect the module to the controller after I had to renew my Niko Hobby API?

**Comment by MirandaPoth** [comment]
Change the password in configuration.yaml. If it gives error ‘connection refused’ see my answer to a previous issue here https://github.com/joleys/niko-home-control-II/issues/31#issuecomment-1264681380

**Comment by sweebel** [comment]
@MirandaPoth can confirm your solution with changing the token in .storage/core.config_entries.py ! 
@jordireusens don't forget to close this issue ;-)

**Comment by tijsverkoyen** [comment]
I have some experience. I will get a look at it if I find the time.

**Comment by tijsverkoyen** [comment]
What would be the best way in your opinion:

1. Just ask the new API key
2. Rerun the full configuration flow?

**Comment by joleys** [comment]
I'd think that option 2 would fit most of the reconfigurations.  The IP and username are more 'fixed' settings.
Do you agree?

**Comment by tijsverkoyen** [comment]
From what I can see I can force the integration to a state that it shows a notification to reconfigure the integration. For instance when we get a connection error. From my point of view I would think only re-entering the API key would be more user friendly as it is the only think that changes.

But I will see how easy it is to achieve

**Comment by tijsverkoyen** [comment]
Is there anybody who has an expired key at the moment? If so: could you check the logs and give me the exact error?

**Comment by MirandaPoth** [comment]
@tijsverkoyen I made a note of it last time I had it. 'Exception: Connection refused - not authorised’ from nhc2_coco/coco.py

**Comment by tijsverkoyen** [comment]
Ok, I think I have implemented the renewal of the API key.

## Config flow
@joleys I think it would be beneficial to refactor the whole config flow, as it is fairly complicated in my opinion. Rerunning the full configuration again is not that easy as seems to be some dependencies which are not available at the reauth step. Therefore I have chosen to just aks the API key. 
Refactoring the config flow is another project. If I find the time I will create a PR.

## Reloading the integration
I tried to reload the configuration when the new API key is validated with the following code at [custom_components/nhc2/config_flow.py#L193](https://github.com/tijsverkoyen/niko-home-control-II/blob/38-renew-hobby-api/custom_components/nhc2/config_flow.py#L193):

````python
await self.hass.config_entries.async_reload(config_entry.entry_id)
````

But when it is executed the config is not reloaded. It also gets a yellow border on the overview of all integrations. 
I can't find a real reason why this is happening. Also not that much documentation available around this topic, or I am not able to find it.

## Testing
Does anybody know a decent way to test the expiring of the key?
If anybody is willing to test: feel free! 

Feedback is appreciated.


@joleys is there a way (discord/slack/...) where we could discuss this integration realtime?

**Comment by tijsverkoyen** [comment]
Any feedback?

**Comment by MirandaPoth** [comment]
> Does anybody know a decent way to test the expiring of the key?

I guess the easiest way to test is just to give an incorrect key in configuration.yaml. 

- Is such a test sufficient? I've had nhc2 for a while so it was installed manually not via the UI.
- I can test this on Thursday if no-one can test sooner?

**Comment by MirandaPoth** [comment]
I've tested this today and it works great. After restarting HA with an old/incorrect API key, the Integrations page shows a red message saying that the Niko integration needs attention, with a 'Configure' button. Clicking the button brings up a box where you can input the new API key. This checks it's correct then tells the user to restart HA for it to take effect. After restarting, everything works as expected.

Note that the new API key is NOT saved in configuration.yaml. This is fine, but perhaps should be mentioned somewhere.

Thanks very much @tijsverkoyen !!

**Comment by joleys** [comment]
@MirandaPoth: thanks for testing and confirming!
@tijsverkoyen: should I merge PR #42?

**Comment by tijsverkoyen** [comment]
@joleys I will try to clearify that the key is not saved in configuration.yaml
Probably by the end of the week.

**Comment by tijsverkoyen** [comment]
@joleys I improved the copy. You can merge https://github.com/joleys/niko-home-control-II/pull/42

**Comment by tijsverkoyen** [comment]
@joleys I think this issue can be closed
