### ISSUE TITLE
Feature request - Integration Digital Meter (BE)

### ISSUE THREAD

**Issue by BenjaminCes** [joleys/niko-home-control-II#45]
Hi,

This is a great add-on for my Home Assistant!

I'm wondering if there is already an integration available to use the values from our digital meter to setup the Energy-module inside HA?

THe data should be available according to the Niko Developers, using the brand new Niko Bridge for NHC2: ( https://www.niko.eu/nl-be/onze-producten/huisautomatisering/wireless-bridge)

**Comment by thomas-svrts** [comment]
Did you try this?
https://www.home-assistant.io/integrations/dsmr/
works without Niko…

**Comment by BenjaminCes** [comment]
Anyone with a screenshot in his configuration.yaml that is functioning for these steps?

![image](https://user-images.githubusercontent.com/50412359/217634764-215d557c-4855-44a0-8cba-b5027acf185e.png)

**Comment by tijsverkoyen** [comment]
At this point the data is not available through the MQTT broker for the digital meter. 

In [v3.0.0](https://github.com/joleys/niko-home-control-II/pull/49) the energy meters that are exposed will be available. Somewhat the same as in the current version. But note that they don't expose any totals but the current usage.

The screenshot in your last comment is to use the current power in the energy dashboard. Note that Niko only exposes the electrical power (in Watt) and not the Electrical Energy (in Watt-hour). You can use the [Riemann sum integral ](https://www.home-assistant.io/integrations/integration/)to convert power to energy.

**Comment by BenjaminCes** [comment]
> At this point the data is not available through the MQTT broker for the digital meter.
> 
> In [v3.0.0](https://github.com/joleys/niko-home-control-II/pull/49) the energy meters that are exposed will be available. Somewhat the same as in the current version. But note that they don't expose any totals but the current usage.
> 
> The screenshot in your last comment is to use the current power in the energy dashboard. Note that Niko only exposes the electrical power (in Watt) and not the Electrical Energy (in Watt-hour). You can use the [Riemann sum integral ](https://www.home-assistant.io/integrations/integration/)to convert power to energy.

Can you provide with a screenshot or copy from your configuration.yaml to get this to work with the current values as you describe?

**Comment by tijsverkoyen** [comment]
I don't use yaml configuration.
I have the Niko Zigbee Outlets and these are exposing the realtime power usage. 
To use them in the energy dashboard I use the Riemann sim integral. If you add the integration you can select a source entity (the power usage).The newly created entity can be used in the energy dashboard to reflect the energy usage.

**Comment by BenjaminCes** [comment]
> 

How do you capture the sum of all your current power usage? With your method, you can only measure it using the sum of separate Zigbee outlets (which I also do have in place, but only for washdisher, washing machine, refrigerator, ... but I want to have the sum of all (as seen on the Digital Meter)

**Comment by tijsverkoyen** [comment]
I don't. I have a (non Niko) electricity clamp that measures the total energy usage.

**Comment by BenjaminCes** [comment]
> I don't. I have a (non Niko) electricity clamp that measures the total energy usage.

Which one do you use?

**Comment by tijsverkoyen** [comment]
https://www.slimmedingen.nl/aeotec-z-wave-plus-energiemeter-1-klem-60a.html?id=234897240

But if you have a digital meter, why don't you integrate that into Home Assistant? See https://github.com/joleys/niko-home-control-II/issues/45#issuecomment-1380942331

**Comment by joleys** [comment]
Are you looking to get the value of the Digital Meter from the integration?
Or do you want to get the sum of all available power meters in you HA setup?  There is no helper currently available, but you can add a summer into you configuration.yaml (https://community.home-assistant.io/t/how-to-sum-energy-and-power-sensors/172779/8).

**Comment by BenjaminCes** [comment]
> Are you looking to get the value of the Digital Meter from the integration? Or do you want to get the sum of all available power meters in you HA setup? There is no helper currently available, but you can add a summer into you configuration.yaml (https://community.home-assistant.io/t/how-to-sum-energy-and-power-sensors/172779/8).

Values from Digital meter.

Since Niko has the Hobby API, and I have the Module which connects the Digital Meter with NHC2 (550-00640), this data should be available using the Hobby API (and this (great) integration) preferably? I don't want to add any other data, if possible.

**Comment by tijsverkoyen** [comment]
@BenjaminCes Are you already using the [v3.0.0](https://github.com/joleys/niko-home-control-II/pull/49) version? Could you share your device list with me please?

**Comment by tijsverkoyen** [comment]
I will close this issue as there is no response.
