### ISSUE TITLE
NHC compatibility

### ISSUE THREAD

**Issue by Artiles86** [joleys/niko-home-control-II#48]
Hello, 
Is there a way to make it compatible with the niko home control v1 ?
The official integration for home-assistant is working fine but I can only list the lights.
I have now integrate the energy module but the HA integration doesn't list the entities for energy.
I found this hacs and I was very interested. THen I installed it and provide the ip of the nhc gateway but it was not working.

Is this integration supposed to be compatible or not ?
If not how could we make it compatible ? I can help if needed.

Thanks for your feedback.

**Comment by dimitridelanghe** [comment]
Contact your local Niko installer or Niko directly for a small amount u can upgrade your installation and much more future proof!
3 months ago, i know someone who has paid xx€ and return his NHC1 to Niko for the new one, good service!

**Comment by tijsverkoyen** [comment]
This is not on our roadmap.
As @dimitridelanghe suggested, I would recommend to upgrade to NHC2.

Note that there is also an official integration for Niko Home Control (1): https://www.home-assistant.io/integrations/niko_home_control/
