### ISSUE TITLE
PIR integration

### ISSUE THREAD

**Issue by dimitridelanghe** [joleys/niko-home-control-II#5]
Hi,
is it possible that the PIR's can be integrated?
I want to help as test user if needed!

**Comment by sebakerckhof** [comment]
It's been a while since I investigated the niko MQTT protocol, but I think there were no messages for PIR detections being send.
I worked around it by having a PIR toggle a virtual switch and use that switch instead

**Comment by dimitridelanghe** [comment]
> It's been a while since I investigated the niko MQTT protocol, but I think there were no messages for PIR detections being send. I worked around it by having a PIR toggle a virtual switch and use that switch instead

Well, this is why internet/github exists, such an easy solutions and i didn't think about this.
Nice 1 Seba!

**Comment by krmarien** [comment]
@sebakerckhof What kind of device are you using as switch? I tried "Virtual Device" and "Other Switched Devices", but none of them are visible on MQTT.

**Comment by dimitridelanghe** [comment]
@krmarien did u fixed this, i should have an other look because i did not manged to integrate the PIR, did you?

**Comment by krmarien** [comment]
In Niko Home Control Programming Software I connected the PIR with a Virtual Device.

Those Virtual Devices are with the latest version of this integration visible in HomeAssistant. However first I was using a Touchscreen profile and they didn't show up. After switching to the Hobby API account they showed up.
No idea if it was a temp issue, never switched back

**Comment by tijsverkoyen** [comment]
@dimitridelanghe did the answer from @krmarien solved your problem? Can this issue be closed?

**Comment by tijsverkoyen** [comment]
I will close this issue as there is no feedback. 
Feel free to reopen the issue if it is not resolved.

**Comment by dimitridelanghe** [comment]
haven't got time to review it, i will try to have a look this weekend!
