### ISSUE TITLE
NHC2 Wall Switch in combination with Smart Light Bulbs

### ISSUE THREAD

**Issue by raf-theunis-kbc-be** [joleys/niko-home-control-II#52]
Hey all,

I'm trying to use the wall switch of my NHC2 installation to control my IKEA Tradfri smart lights via HA.
The problem is that the wall switch actually cuts the power to the light bulbs, which is not the intended behaviour.
So basically, when pressing the wall switch, I want to send an event to HA to turn off the IKEA light bulbs without cutting the actual power.

Is this something that is possible? If yes, how? :) 

Thanks in advance!

**Comment by tijsverkoyen** [comment]
To be honest: I don't think so.

You could try to:
1. Bypass the switch to provide always power to the light
2. Remove the light from the Routine in Niko Home Control Software
3. Check is you can see any incoming messages in the MQTT and act on that.

But to my knowledge in the current state of the integration not all NHC Devices are supported so I don't think there will be incoming messages in the integration.

**Comment by thomas-svrts** [comment]
Cant you link it to virtual devices?
And act upon those virtual devices within HA…

**Comment by raf-theunis-kbc-be** [comment]
Thanks for the information!

@thomas-svrts, those virtual devices are something you setup in the Niko programming software?

**Comment by user152306** [comment]
@raf-theunis-kbc-be yes, you create a virtual device and bind that to the button instead of the ligth bulbs it is bound to now. Then you configure what you want to happen in HA based on that virtual device. 

It is also possible to use a wall button for two things in NHC buy configuring long press action with the button as well.

**Comment by raf-theunis-kbc-be** [comment]
> 

Wow awesome! And all this is working with this HA integration?
Will try it out this evening when I get home!

**Comment by tijsverkoyen** [comment]
I don't think virtual devices are supported yet. But I can be wrong.

**Comment by raf-theunis-kbc-be** [comment]
> I don't think virtual devices are supported yet. But I can be wrong.

Only one way to find out then! :)

**Comment by thomas-svrts** [comment]
I never tried it with HA. But I want to try it for my hue lights… till now didnt found the time to test.
I read this was a feature in some domotics addon.  So should be developable.

**Comment by user152306** [comment]
@raf-theunis-kbc-be yes, I use virtual devices both to trigger things from NHC to HA and from HA to NHC. In my mind "there is nothing you can't do" between NHC and HA in terms of buttons/automations/actions/scenes since NHC is very flexible with how you can setup conditions etc.

**Comment by raf-theunis-kbc-be** [comment]
Nice! That virtual device you are talking about, is it the same as a virtual output mentioned here? https://guide.niko.eu/display/SMNHC1/Conditions+and+virtual+outputs

**Comment by user152306** [comment]
That is for NHC1, I don't know how that works.

It's mentioned here for NHC2: https://guide.niko.eu/pages/viewpage.action?pageId=45223489
When you create it, there is a option you click for "make it usable from the app" or something, I always click that option for the ones I want to control from HA, haven't tested without it (it also gives me a button in the phone-app which can be good for redundancy :) ).

**Comment by raf-theunis-kbc-be** [comment]
> 

Sure no problem. Would be nice if you could check it when behind the system, but in the meantime I will already try some stuff out! Thanks again for all the valuable info!

**Comment by raftheunis87** [comment]
@user152306 

I did make some changes in my NHC2 Programming Software:

- Made a virtual device
- Removed the existing basic action for the lights
- added a new basic action to the virtual device

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3533046/216143330-ab90f4f2-2d7b-4d3d-b3df-2e4b3e8d37b2.png">


Does this look ok to you? I'm pretty new to the NHC programming stuff.

**Comment by user152306** [comment]
Yes, that looks correct to me in NHC2.
For triggering in HA based on an event i NHC2, I use the binary-sensor and in the automation trigger on the on/off.

Btw, what I mentioned earlier with the "appear in the app" is on basic actions as you see in your printscreen. I guess this is needed to click if there is no physical button connected to the basic action, otherwise you would maybe get a warning message when uploading the config.

I would say that I'm not that good with NHC2 either, everytime I want to do something and figure it out I realize how little understand about what I can do :D

Looking at my NHC config, theese are some things I have done that is used from HA:
- If there is a movement based on a PIR, that routine is true as a binary sensor and I can act on that in HA.
- If there is a NC/NO event on the input-module, I have a condition that sets a virtual device to true and I can act on that in HA.
- A basic action with "this basic action should only appear in the app...." clicked triggers a on/off (or true/false) on a device in NHC, and that basic action is then a "switch" in HA. (All your light buttons works like this from HA as well)

**Comment by raf-theunis-kbc-be** [comment]
> Yes, that looks correct to me in NHC2. For triggering in HA based on an event i NHC2, I use the binary-sensor and in the automation trigger on the on/off.
> 
> Btw, what I mentioned earlier with the "appear in the app" is on basic actions as you see in your printscreen. I guess this is needed to click if there is no physical button connected to the basic action, otherwise you would maybe get a warning message when uploading the config.
> 
> I would say that I'm not that good with NHC2 either, everytime I want to do something and figure it out I realize how little understand about what I can do :D
> 
> Looking at my NHC config, theese are some things I have done that is used from HA:
> 
> * If there is a movement based on a PIR, that routine is true as a binary sensor and I can act on that in HA.
> * If there is a NC/NO event on the input-module, I have a condition that sets a virtual device to true and I can act on that in HA.
> * A basic action with "this basic action should only appear in the app...." clicked triggers a on/off (or true/false) on a device in NHC, and that basic action is then a "switch" in HA. (All your light buttons works like this from HA as well)

@tijsverkoyen FYI, Virtual devices do work with the NHC2 integration in HA (both on hobby api and touch profile).

@user152306, thanks again for the information, it's working like a charm now!

**Comment by raftheunis87** [comment]
@user152306 do you perhaps also have the Niko video doorbell? Can't get it to work in HA.

**Comment by nexus256** [comment]
> @user152306 do you perhaps also have the Niko video doorbell? Can't get it to work in HA.

I've used motionEye for all of my camera's (Dahua) including the Niko video doorbell.
The URL is: rtsp://<ip of your videophone>/rtsp/video.av

Username & password on page 59 of this manual: https://www.robintele.com/images/downloads/Manual_RobinSV_v3.2.3_NL.pdf

**Comment by raf-theunis-kbc-be** [comment]
> > @user152306 do you perhaps also have the Niko video doorbell? Can't get it to work in HA.
> 
> I've used motionEye for all of my camera's (Dahua) including the Niko video doorbell. The URL is: rtsp://ip_of_your_videophone/rtsp/video.av
> 
> Username & password on page 59 of this manual: https://www.robintele.com/images/downloads/Manual_RobinSV_v3.2.3_NL.pdf

I do get a RTSP authentication pop-up when opening that URL, but it doesn't accept the default credentials.
I'm testing this in VLC. 

Since this is unrelated to my original github (NHC2) issue, is there a way that I can discuss this with you @nexus256 ?

**Comment by raftheunis87** [comment]
For what it is worth, I'm having this kit: https://www.niko.eu/en/products/door-communication/digital-solutions/video-kit-2-wire-with-access-control-module-external-and-internal-video-unit-productmodel-niko-65aa624b-007c-5e06-8224-a11f834d7233

So it's not hooked up to my Niko Connected Controller.

**Comment by nexus256** [comment]
> For what it is worth, I'm having this kit: https://www.niko.eu/en/products/door-communication/digital-solutions/video-kit-2-wire-with-access-control-module-external-and-internal-video-unit-productmodel-niko-65aa624b-007c-5e06-8224-a11f834d7233
> 
> So it's not hooked up to my Niko Connected Controller.

Seems that this 2 wire system is based on Hikvision and not Robin. 
Perhaps this helps?

https://www.hikvision.com/europe/products/Video-Intercom-Products/Kits/2-wire-Kits/ds-kis702/
And
https://www.google.com/url?sa=t&source=web&rct=j&url=https://us.hikvision.com/en/system/files_force/manual/qsg_ds-kis701_video_intercom_bundle_080519na.pdf%3Fdownload%3D1&ved=2ahUKEwiIhdGwkPv8AhUuhv0HHWEtCCAQFnoECCMQAQ&usg=AOvVaw1VdNt94bADQGgOIKnkntTn

**Comment by raf-theunis-kbc-be** [comment]
> 

Thanks for the links!

Seems like that username/password combo is not working :(
