### ISSUE TITLE
Switch events are not received

### ISSUE THREAD

**Issue by FHannes** [joleys/niko-home-control-II#66]
I've noticed after the update to version 3.x that I am no longer receiving events from light switches. I can still turn them on or off from home-assistant, but their state is not updated from the API as far as I can tell.

**Comment by tijsverkoyen** [comment]
@FHannes what do you mean by "Light switches"? Is suspect you mean the light entity for a non dimmable light?

And what is not updated?
1. If you toggle the light in HA, is the actual light toggled? But the switch in HA is not updated to the new state?
2. if you toggle the light with a button in your house, the switch in HA is not updated to the new state?

Could it be that a new version was uploaded to your Niko Home Controller? Or that the power went down? Or you Controller had been rebooted. But Home Assistant not?

Could you try to restart Home Assistant and see if it works again?

**Comment by FHannes** [comment]
Hi tijs, this was affecting all of my switches, single, double, dimmable... But I believe you are correct. My controller was updated. I had restarted HA already, but now after a few more restarts it seems to have sorted itself out. Thanks 👍

**Comment by tijsverkoyen** [comment]
@FHannes glad it is resolved. I have a PR open to add an entity that shows if HA should be restarted. See https://github.com/joleys/niko-home-control-II/pull/67
