### ISSUE TITLE
Add ability to update config - Username, Password, HobbyToken

### ISSUE THREAD

**Issue by samuel-verdonck** [joleys/niko-home-control-II#75]
If one of the following changes the integration breaks. There is no UI/Flow to update the initial values. 
Need to delete and re-integrate.

**Comment by tijsverkoyen** [comment]
@samuel-verdonck weird, as normally if the authentication fails it should let you reconfigure the integration. Are you 100% sure you are using the latest version of the integration?

**Comment by samuel-verdonck** [comment]
It was a change in IPaddress... 🤦‍♂️ so my bad.
