### ISSUE TITLE
Energy dashboard integration

### ISSUE THREAD

**Issue by TheMrBlue** [joleys/niko-home-control-II#76]
Hello

Is there any possibility to enable integration of power consumption/generation into the energy dashboard?
Thanks for the great work!

**Comment by joleys** [comment]
You can check the info in the [readme](https://github.com/joleys/niko-home-control-II#generic-zigbee-smart-plug) regarding the totalizers.

**Comment by TheMrBlue** [comment]
> You can check the info in the [readme](https://github.com/joleys/niko-home-control-II#generic-zigbee-smart-plug) regarding the totalizers.

Hi Jo, apologies I should have checked there first. Thanks!
