### ISSUE TITLE
Removed old NHC2 integration (Filip) and installed new v3.1.1, followed the wizzard but no devices are showing?

### ISSUE THREAD

**Issue by roelteeuwenNL** [joleys/niko-home-control-II#77]
Dear all,

I just removed the old NHC2 integration form HACS and installed the new v3.1.1, I would love to see all new functions!
But somehow no devices are showing up?
I followed these steps:
1. Removed the old integration and HACS component
2. I installed the new v3.1.1 custom HACS component and then the integration. I followed the wizzard. The wizzard found my Niko controller IP. Then I use the "hobby" profile (hobby is also the username of the API token) and the password is the API token (I copy/pasted it form the API token screen)
3. The pop-up shows "Gelukt! Configuratie gemaakt voor hobby (niko). Then I press finish.  -> no entities
4. Rebooted HAS -> no entities

Please help. Any ideas? Thanks!!

**Comment by tijsverkoyen** [comment]
Can you enable debug-mode and see if there is a device list in the logs? See https://github.com/joleys/niko-home-control-II#found-a-bug
Which version of Home Assistant are you using?

**Comment by roelteeuwenNL** [comment]
Hi Tijs, thanks for your fast reply!I’m going to check this, hopefully in the weekend of June the 10th and will post my findings 👍Best regards Roel Sent from my iPhoneOp 30 mei 2023 om 11:04 heeft Tijs Verkoyen ***@***.***> het volgende geschreven:﻿
Can you enable debug-mode and see if there is a device list in the logs? See https://github.com/joleys/niko-home-control-II#found-a-bug
Which version of Home Assistant are you using?

**Comment by jonassmets** [comment]
@tijsverkoyen I have the same issue. I'm working with a new setup. A VM on a Synology NAS. Using latest version of NHC on a connected controller. Loggin in with hobby + api key. But now devices are showing.

**Comment by jonassmets** [comment]
@tijsverkoyen solved the issue. Adding the controller manually by IP address instead of choosing the presented controller fixed it.

**Comment by roelteeuwenNL** [comment]
Hi @tijsverkoyen, where/how can I add the controller manually by IP address? Thanks 😁👍

**Comment by itayp** [comment]
@tijsverkoyen @jonassmets are you guys talking about:
nhc2:
  host: 192.168.107.3
  username: hobby
  password: !secret nhc2_password
  port: 8884

If so - I assume in the password line we put the API key we got from Niko?

**Comment by tijsverkoyen** [comment]
You should not use the yaml configuration, but only use the wizard.

**Comment by itayp** [comment]
Thanks @tijsverkoyen - but if I follow the wizard - nothing happens. I get an OK then the Hobby or Profile (whatever I chose) appears in the UI with no devices/entities.
See attached (MAC address removed)
![Niko not working](https://github.com/joleys/niko-home-control-II/assets/1978895/aa59b76b-db05-486c-ab6b-5eecb837c0d3)

**Comment by jonassmets** [comment]
@itayp Did you add the hub by manually adding the ip address?

**Comment by roelteeuwenNL** [comment]
Hi! I used the API key from NHC2 in the password field during the wizzard. Would that normally be correct?So I need to type in manually the IP address during the wizard or should I manually type in the IP address elsewhere?Best regards RoelSent from my iPhoneOp 28 jun. 2023 om 08:08 heeft itayp ***@***.***> het volgende geschreven:﻿
@tijsverkoyen @jonassmets are you guys talking about:
nhc2:
host: 192.168.107.3
username: hobby
password: !secret nhc2_password
port: 8884
If so - I assume in the password line we put the API key we got from Niko?

**Comment by tijsverkoyen** [comment]
Can you try the following steps:

1. Remove the integration
2. Remove al related configuration from `configuration.yaml`
3. Re-add the integration
4. Fill in the IP address manually instead of selecting the proposed controller

**Comment by itayp** [comment]
Thanks @tijsverkoyen  - it's now working as expected!
Finally.

May I suggest on the wizard it will be clear for hobby "profile" you need to insert the API KEY as the password?
It might be worth also showing a sample screen of expected behavior. Meaning after that step you should already get the "devices discovered" list with a prompt to put them in the different rooms/areas. Because before,  I got a "success", and I assumed the devices will pop up in my devices list. Which clearly is not the expected behavior.

**Comment by tijsverkoyen** [comment]
@itayp Glad it works!

Feel free to make a pull request with improved docs, or screenshots.

The list of devices discovered will be shown only if the device list is returned at that moment, it can take some time for large installations, therefore it is not guaranteed that the list is shown when you add the integration.
