### ISSUE TITLE
Dimming with 0-10 or 1-10v

### ISSUE THREAD

**Issue by J13K13** [joleys/niko-home-control-II#78]
Hi all,

Would dimming with the 0-10 or 1-10v module play nice with home assistant?

Is there a discord or forum for discussing this integration? About to build a new nhc2 install and looking for ideas/best practices to integrate with HA. 

Best regards

**Comment by tijsverkoyen** [comment]
@J13K13 has this answered your question? Feel free to reopen this issue if not.
