### ISSUE TITLE
"energyhome Electrical Power from Grid" stops updating

### ISSUE THREAD

**Issue by BenjaminCes** [joleys/niko-home-control-II#79]
Hi,

I have NHC2 setup with bridge module installed to the Digital Meter (Belgium). 

After a reboot, I notice that the stats from Power to grid or grid to power are updated correctly every x seconds, but after a time, the update stops and remains the same wattage until I reboot the Home Assistant again. 

What can be done or can I deliver you some extra logs?

**Comment by tijsverkoyen** [comment]
Hi BenjaminCes
Can you enable the debugging: see https://github.com/joleys/niko-home-control-II#found-a-bug

There should be something like "..._report_instant_usage re-enabled."

**Comment by BenjaminCes** [comment]
[home-assistant_2023-06-26T20-37-41.476Z.log](https://github.com/joleys/niko-home-control-II/files/11873926/home-assistant_2023-06-26T20-37-41.476Z.log)
Logs attached

**Comment by tijsverkoyen** [comment]
@BenjaminCes Some questions:
* Is it for all devices that the reporting stops, or a specific device?
* I see the `Report Instant Usage re-enabled` message in the logs you provide, so the message to report the usage is sent
* I also see the property `ReportInstantUsage` changes to `True`, so it should update. 
* Are you using the latest version of the Niko Home Control software?

At this point I think you will need to contact Niko and ask them if there is any reason that the usage stops reporting / stays the same.

**Comment by BenjaminCes** [comment]
Fixed after full reinstall of Home Assistant (moved from RPi to NUC where HA is running in Docker-mode)

Working like a charm now.

Only remark, we're unable to add the value of 'return to grid' to the default Energy-tab from HA itself?
