### ISSUE TITLE
Muting doorbell on touch screen?

### ISSUE THREAD

**Issue by flimofly** [joleys/niko-home-control-II#88]
The Niko touch screen also act as a speaker, ringing when someone is at the door (through Niko video door station).  It's possible to mute the touch screen sound but I would would like to automate this so that the speaker is muted after a certain time of day. 

As far as I understand, the touch screen is neither accessible via the api, nor the Niko programming software.

**Comment by tijsverkoyen** [comment]
I don't own a [RobinsIP Videodoorstation](https://github.com/joleys/niko-home-control-II/issues/88#robinsip-videodoorstation), so I can't assist in this exact question

In theory everything that is possible in the Niko Home app for your phone is possible in Home Assistant. 

In the device list of someone else I see there is a parameter exposed `SpeakerVolume`, but this is not controllable. So I suspect it is not possible to change the volume.

**Comment by tijsverkoyen** [comment]
@joleys do you know if this is possible?

**Comment by joleys** [comment]
I cannot find anything in the Niko API documentation, but we know not everything is in there.  I tried some commands via MQTT but was unable to change the volume settings.
The Robin manual for their API shows a curl command to mute the audio:
`curl -u admin:<password> "http://<address>/api/v1/mute _ set?mute=tones _ incoming"`

Does this info help?

**Comment by flimofly** [comment]
I will give it a try, thx. I wonder whether this will work, given that the sound comes from the Niko touch screen, not the door station. That said, perhaps muting the door station will have the same effect.On 29 Sep 2023, at 19:50, Jo Leys ***@***.***> wrote:﻿
I cannot find anything in the Niko API documentation, but we know not everything is in there.  I tried some commands via MQTT but was unable to change the volume settings.
The Robin manual for their API shows a curl command to mute the audio:
curl -u admin:<password> "http://<address>/api/v1/mute _ set?mute=tones _ incoming"
Does this info help?

**Comment by tijsverkoyen** [comment]
@flimofly did it work?

**Comment by tijsverkoyen** [comment]
@flimofly any update? Did it work.
I will close this issue for now. If not: feel free to reopen it.
