### ISSUE TITLE
Cover status wrong when motor is moving

### ISSUE THREAD

**Issue by nexus256** [joleys/niko-home-control-II#91]
If I close my covers, the moving status indicates 'Opening'

If I open my covers, the moving status indicates 'Closing'

 

When the motor stops the status of the cover is correct, also the status of the sensor.<name>_last_direction is correct.

Its only when the cover is moving it is indicating the wrong action.

 

Someone else has the same behavior?

**Comment by tijsverkoyen** [comment]
Hmm, I thought I tested this.
I think the "bug" will be present in https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py#L46

**Comment by davidvf** [comment]
Hi @nexus256 i just checked on my setup, i have exactly the same behaviour.

Another thing i noticed, if i manually set a cover to eg 50%, it's not in the middle at all. (But this is completely unrelated to this)

**Comment by tijsverkoyen** [comment]
Where do you see this "moving status"? Could you create a screenshot and point where the "Opening" / "Closing" is shown?

I suspect the `Moving` property s not true. Or that last_direction is already set on the "new" value.


In the later it can be fixed by changing the code in https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py

[line 50](https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py#L50) from

```python
if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_CLOSE:
```

to

```python
if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_OPEN:
```

and
[line 60](https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py#L60) from

```python
if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_OPEN:
```

to

```python
if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_CLOSE:
```

Is anyone willing to change this and confirm this fixes the issue?
Would anybody

**Comment by nexus256** [comment]
Hi Tijs,

Changing lines 50 & 60 fixed the issue for me.





Sent from my Galaxy



-------- Original message --------
From: Tijs Verkoyen ***@***.***>
Date: 29/11/23 13:46 (GMT+01:00)
To: joleys/niko-home-control-II ***@***.***>
Cc: nexus256 ***@***.***>, Mention ***@***.***>
Subject: Re: [joleys/niko-home-control-II] Cover status wrong when motor is moving (Issue #91)


Where do you see this "moving status"? Could you create a screenshot and point where the "Opening" / "Closing" is shown?

I suspect the Moving property s not true. Or that last_direction is already set on the "new" value.

In the later it can be fixed by changing the code in https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py

line 50<https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py#L50> from

if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_CLOSE:

to

if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_OPEN:

and
line 60<https://github.com/joleys/niko-home-control-II/blob/master/custom_components/nhc2/nhccoco/devices/motor_action.py#L60> from

if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_OPEN:

to

if self.is_moving and self.last_direction == PROPERTY_LAST_DIRECTION_VALUE_CLOSE:

Is anyone willing to change this and confirm this fixes the issue?
Would anybody

**Comment by davidvf** [comment]
Indeed, those changes are the solution for me as well. 
Thanks!

**Comment by tijsverkoyen** [comment]
Thx for your feedback. 
I have created the [v3.3.1](https://github.com/joleys/niko-home-control-II/releases/tag/v3.3.1) release. Which includes the required changes.
