### ISSUE TITLE
Gas and water consumption 

### ISSUE THREAD

**Issue by Rinusesa** [joleys/niko-home-control-II#92]
Dear all

I noticed that it’s not possible to add the water and gas consumption… it’s connected to a pulse counter module. Is it coming in the future ?

**Comment by tijsverkoyen** [comment]
This is a duplicate for https://github.com/joleys/niko-home-control-II/issues/6
I don't know if it is coming, but feel free to contact Niko directly to ask them ;-)

**Comment by vliere** [comment]
Can you add the pulse counter module to the integration?

**Comment by tijsverkoyen** [comment]
Is it exposed in the device list?

**Comment by vliere** [comment]
No, it is not detected by the NHC2 integration
