### ISSUE TITLE
Control zone valve 

### ISSUE THREAD

**Issue by jonassmets** [joleys/niko-home-control-II#93]
I'm running into a problem with NHC and I hope I can get a workaround, true hoas. In NHC you can't have 2 zone valves controlled by 1 thermostat or digital black. So you can only control 1 of the 2. I was hoping I could control the zone valve directly, true hoas. As the only thing that needs to happen is put it on or off. Of course, I also have to send a command to the heating system.  
It looks like heating system and zone valves are not available in hoas. Can this be added?

**Comment by tijsverkoyen** [comment]
What do you mean by "hoas"? Home Assistant?

I don't think it is possible. But if you are willing to share your device list with me (https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list), I can take a look. But I don't remember any valves to be exposed, only the thermostats.

**Comment by jonassmets** [comment]
Yes, sorry. Home assistant Op 13 nov 2023 om 09:23 heeft Tijs Verkoyen ***@***.***> het volgende geschreven:﻿
What do you mean by "hoas"? Home Assistant?
I don't think it is possible. But if you are willing to share your device list with me (https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list), I can take a look. But I don't remember any valves to be exposed, only the thermostats.

**Comment by tijsverkoyen** [comment]
@jonassmets are you willing to share the device list?

**Comment by jonassmets** [comment]
@tijsverkoyen sure! How do I do this?

**Comment by blatruwe** [comment]
https://github.com/joleys/niko-home-control-II#i-need-to-see-the-device-list

**Comment by tijsverkoyen** [comment]
@jonassmets any news on this?
